<?php

/**
 * ENVIRONMENTS
 *
 * TFD allows for your standard development, testing, and production environments.
 * Set the variables (MySQL, error reporting, or anything else you want) for each here
 *  and then for each site, define the environment inside of your .htaccess file (default DEVELOPMENT)
 *
 * TFD includes a custom error reporting class.
 * It is used to report errors that are generated by TFD, not PHP.
 * If "testing mode" is off, it will display, email, or log the error and then try to finish running the script.
 * If testing mode is on, it will display the error (along with logging it or emailing it) and then stop the script.
 *
 * REDIS
 * -----
 * Default Redis port is 6379
 *   If you do not have your Redis server password protected,
 *    leave the password field blank.
 */

class Environment{

	function __construct($env){
		// load some global config options
		$this->general_config();
		$this->api_keys();
		
		// call specific environment settings
		$env = strtolower($env);
		$this->$env();
	}
	
	function general_config(){
		define('MAINTENANCE_MODE', false);
		
		define('SITE_TITLE', 'Tea-Fueled Does');
		define('ADMIN_EMAIL', '');
		
		define('LOGIN_PATH', 'login');
		define('ADMIN_PATH', 'admin');
		define('USERS_TABLE', 'users'); // the MySQL table the user info is store in
		define('AUTH_KEY', '123456'); // a custom key to validate users, change this
		define('LOGIN_TIME', 3600); // time to stay logged in via cookie
		
		define('ERROR_LOG_LOCATION', BASE_DIR.'error.log');
		
		define('MAGIC_AJAX_PATH', 'ajax');
	}
	
	function api_keys(){
		// ReCAPTCHA - http://www.google.com/recaptcha
		define('RECAPTCHA_PUBLIC_KEY', '');
		define('RECAPTCHA_PRIVATE_KEY', '');
		
		// Postmark - http://postmarkapp.com/
		define('POSTMARK_API_KEY', '');
		define('POSTMARK_FROM', '');
		define('POSTMARK_REPLY_TO', ''); // not required
		
		// Amazon S3 - http://aws.amazon.com/s3/
		define('S3_ACCESS_KEY', '');
		define('S3_SECRET_KEY', '');
		define('S3_DEFAULT_BUCKET', '');
		define('S3_DEFAULT_ACL', 'public-read');
	}
	
	/**
	 * ENVIRONMENTS
	 */
	
	function development(){
		define('BASE_URL', 'http://localhost/'); // with trailing slash
		// php error reporting
		error_reporting(E_ERROR | E_WARNING | E_PARSE);
		// tfd error reporting
		define('TESTING_MODE', true);
		// ablity to add a user with a url (example.com/?add_user&username=user&password=pass)
		define('ADD_USER', true);
		// MySQL
		define('DB_HOST', '127.0.0.1'); // do not use "localhost" (use 127.0.0.1 instead)
		define('DB_PORT', '8889'); // MySQL default is 3306
		define('DB_USER', 'root');
		define('DB_PASS', 'root');
		define('DB', 'tea');
		// Redis
		define('REDIS_HOST', 'localhost');
		define('REDIS_PORT', 6379);
		define('REDIS_PASS', '');
	}
	
	function testing(){
		define('BASE_URL', ''); // with trailing slash
		// php error reporting
		error_reporting(E_ERROR | E_WARNING);
		// tfd error reporting
		define('TESTING_MODE', true);
		// ablity to add a user with a url (example.com/?add_user&username=user&password=pass)
		define('ADD_USER', false);
		// MySQL
		define('DB_HOST', ''); // do not use "localhost" (use 127.0.0.1 instead)
		define('DB_PORT', '3306'); // MySQL default is 3306
		define('DB_USER', '');
		define('DB_PASS', '');
		define('DB', '');
		// Redis
		define('REDIS_HOST', 'localhost');
		define('REDIS_PORT', 6379);
		define('REDIS_PASS', '');
	}
	
	function production(){
		define('BASE_URL', ''); // with trailing slash
		// php error reporting
		error_reporting(0); // no reporting
		// tfd error reporting
		define('TESTING_MODE', false);
		// ablity to add a user with a url (example.com/?add_user&username=user&password=pass)
		define('ADD_USER', false);
		// MySQL
		define('DB_HOST', ''); // do not use "localhost" (use 127.0.0.1 instead)
		define('DB_PORT', '3306'); // MySQL default is 3306
		define('DB_USER', '');
		define('DB_PASS', '');
		define('DB', '');
		// Redis
		define('REDIS_HOST', 'localhost');
		define('REDIS_PORT', 6379);
		define('REDIS_PASS', '');
	}

}