<?php

/**
 * ENVIRONMENTS
 *
 * TFD allows for your standard development, testing, and production environments.
 * Set the variables (MySQL, error reporting, or anything else you want) for each here
 *  and then for each site, define the environment inside of your .htaccess file (default DEVELOPMENT)
 *
 * TFD includes a custom error reporting class.
 * It is used to report errors that are generated by TFD, not PHP.
 * If "testing mode" is off, it will display, email, or log the error and then try to finish running the script.
 * If testing mode is on, it will display the error (along with logging it or emailing it) and then stop the script.
 */

define('ENVIRONMENT', $_SERVER['ENV']);

if(ENVIRONMENT === 'DEVELOPMENT'){
	define('BASE_URL', 'http://localhost/'); // with trailing slash
	// php error reporting
	error_reporting(E_ERROR | E_WARNING | E_PARSE);
	// tfd error reporting
	define('TESTING_MODE', true);
	// ablity to add a user with a url (example.com/?add_user&username=user&password=pass)
	define('ADD_USER', true);
	// MySQL
	define('DB_HOST', 'localhost');
	define('DB_USER', 'root');
	define('DB_PASS', 'root');
	define('DB', 'tfd');
}elseif(ENVIRONMENT === 'TESTING'){
	define('BASE_URL', ''); // with trailing slash
	// php error reporting
	error_reporting(E_ERROR | E_WARNING);
	// tfd error reporting
	define('TESTING_MODE', true);
	// ablity to add a user with a url (example.com/?add_user&username=user&password=pass)
	define('ADD_USER', false);
	// MySQL
	define('DB_HOST', '');
	define('DB_USER', '');
	define('DB_PASS', '');
	define('DB', '');
}elseif(ENVIRONMENT === 'PRODUCTION'){
	define('BASE_URL', ''); // with trailing slash
	// php error reporting
	error_reporting(0); // no reporting
	// tfd error reporting
	define('TESTING_MODE', false);
	// ablity to add a user with a url (example.com/?add_user&username=user&password=pass)
	define('ADD_USER', false);
	// MySQL
	define('DB_HOST', '');
	define('DB_USER', '');
	define('DB_PASS', '');
	define('DB', '');
}