<?php

/**
 * ENVIRONMENTS
 *
 * TFD allows for your standard development, testing, and production environments.
 * Set the variables (MySQL, error reporting) for each here.
 *
 * TFD includes a custom error reporting class.
 * It is used to report errors that are generated by TFD, not PHP.
 * If "testing mode" is off, it will display, email, or log the error and then try to finish running the script.
 * If testing mode is on, it will display the error (along with logging it or emailing it) and then stop the script.
 */

define('ENVIRONMENT', 'DEVELOPMENT'); // DEVELOPMENT, TESTING, PRODUCTION

if(ENVIRONMENT === 'DEVELOPMENT'){
	// php error reporting
	error_reporting(E_ERROR | E_WARNING | E_PARSE);
	// tfd error reporting
	define('TESTING_MODE', true);
	// MySQL
	define('DB_HOST', 'localhost');
	define('DB_USER', 'root');
	define('DB_PASS', 'root');
	define('DB', 'tfd');
}elseif(ENVIRONMENT === 'TESTING'){
	// php error reporting
	error_reporting(E_ERROR | E_WARNING);
	// tfd error reporting
	define('TESTING_MODE', true);
	// MySQL
	define('DB_HOST', '');
	define('DB_USER', '');
	define('DB_PASS', '');
	define('DB', '');
}elseif(ENVIRONMENT === 'PRODUCTION'){
	// php error reporting
	error_reporting(0); // no reporting
	// tfd error reporting
	define('TESTING_MODE', false);
	// MySQL
	define('DB_HOST', '');
	define('DB_USER', '');
	define('DB_PASS', '');
	define('DB', '');
}